# @package _global_
# CV Fold 4: train 1995..2017-12-30 (24h embargo), val 2018-01-01..2021-12-31
data:
  timeseries:
    train_index: "cv5/fold4/train_index.csv"
    validation_index: "cv5/fold4/validation_index.csv"
    stat_file: "cv5/fold4/table_stats.pkl"
