# Experiment: tcn, in1d input, out12h output
# Usage: python scripts/train.py --config-name=in1d_out12h_tcn

defaults:
  - in1d_out12h
  - _self_

experiment:
  name: "in1d_out12h_tcn"

model:
  model_type: "tcn"
