# Experiment: gnn_tcn, in1d input, out24h output
# Usage: python scripts/train.py --config-name=in1d_out24h_gnn_tcn

defaults:
  - in1d_out24h
  - _self_

experiment:
  name: "in1d_out24h_gnn_tcn"

model:
  model_type: "gnn"
  gnn_temporal_type: "tcn"
