# Experiment: gnn_tcn, in2d input, out6h output
# Usage: python scripts/train.py --config-name=in2d_out6h_gnn_tcn

defaults:
  - in2d_out6h
  - _self_

experiment:
  name: "in2d_out6h_gnn_tcn"

model:
  model_type: "gnn"
  gnn_temporal_type: "tcn"
