# Experiment: 3-day input, 6-hour output
# Usage: python scripts/train.py --config-name=in3d_out6h

defaults:
  - local
  - _self_

experiment:
  name: "in3d_out6h"

data:
  timeseries:
    input_start: -144
    input_end: 0
    target_start: 0
    target_end: 12

model:
  model_type: "linear"
