# Experiment: gnn_bilstm, in2d input, out24h output
# Usage: python scripts/train.py --config-name=in2d_out24h_gnn_bilstm

defaults:
  - in2d_out24h
  - _self_

experiment:
  name: "in2d_out24h_gnn_bilstm"

model:
  model_type: "gnn"
  gnn_temporal_type: "bilstm"
