# Experiment: tcn, in2d input, out12h output
# Usage: python scripts/train.py --config-name=in2d_out12h_tcn

defaults:
  - in2d_out12h
  - _self_

experiment:
  name: "in2d_out12h_tcn"

model:
  model_type: "tcn"
