# Experiment: gnn_transformer for in3d out12h
# Usage: python scripts/train.py --config-name=in3d_out12h_gnn_transformer

defaults:
  - in3d_out12h
  - _self_

experiment:
  name: "in3d_out12h_gnn_transformer"

model:
  model_type: "gnn"
  gnn_temporal_type: "transformer"
