# Experiment: tcn for in3d out12h
# Usage: python scripts/train.py --config-name=in3d_out12h_tcn

defaults:
  - in3d_out12h
  - _self_

experiment:
  name: "in3d_out12h_tcn"

model:
  model_type: "tcn"
